### ISSUE TITLE
(feature request) Providing access of YAML file to the an agent 

### ISSUE THREAD

**Issue by jerryIsHere** [GAIGResearch/Stratega#101]
After reading the paper [A Survey of Reinforcement Learning Informed by Natural Language](https://arxiv.org/abs/1906.03926), I think Stratega falls under the task-dependent language information category. 

Although YAML are not natural language, I think most "natural language text " refered in the literature are highly structured and artificial, which are in essence

> synthetic language (automatically generated from a simple grammar and limited vocabulary).

It will be great if it is possible to make YAML file of the game as textual input for the agent. To be specific input for sequential model like LSTM, transformer, abstract syntax tree parser, ect, as some submodule of the agent. Which are now unavaliable for the hidden set of games in a competition.

Relevent research example in this survery are mentioned in (at least) this paragraph:
> [Branavan et al., 2012] learn a Q-function that improves Monte-Carlo tree search planning for the first few moves in Civilization II, a turn-based strategy game, while accessing the game’s natural language manual. Features for their Q-function depend on the game manual via learned sentence-relevance and predicate-labeling models whose parameters are optimised only by minimising the Q-function estimation error. Due to the structure of their hand-crafted features (some of which match states and actions to words, e.g. action == irrigate AND action-word == "irrigate") , these language processing models nonetheless somewhat learn to extract relevant sentences and classify their words as relating to the state, action, or neither. More recently, [Narasimhan et al., 2018] investigate planning in a 2D game environment where properties of entities in the environment are annotated by natural language (e.g. the ‘spider’ and ‘scorpion’ entities might be annotated with the descriptions “randomly moving enemy" and “an enemy who chases you", respectively). Descriptive annotations facilitate transfer by learning a mapping between the annotations and the transition dynamics of the environment.

**Comment by GAIGResearch** [comment]
The agent already has access to the YAML file: https://stratega.readthedocs.io/en/latest/tutorials/exploringGameStates/index.html#game-information
